name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "UV_BIN=$HOME/.local/bin" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
      - name: Sync deps
        run: |
          uv --version
          uv sync --dev
      - name: Lint
        run: uv run ruff check .
      - name: Type check
        run: uv run pyright || true
      - name: Test
        run: uv run pytest -q
